services:
  - type: web
    name: Cyberdock
    env: python
    branch: main
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DB_URL
        value: "postgresql://cyberdock_db_user:6kJ2cQVY2moRxkgGMTROnilAjf3y0qzT@dpg-d1jtonm3jp1c73epht0g-a.oregon-postgres.render.com/cyberdock_db?sslmode=require"
      - key: ML_CLIENT_ID
        value: "5343781526788979"
      - key: ML_CLIENT_SECRET
        value: "XjfB7T8wFqx1aaBI0sesJr8iKrPmU08p"
      - key: BACKEND_URL
        value: "https://cyberdock.onrender.com"
      - key: FRONTEND_URL
        value: "https://cyberdock.onrender.com"
      - key: WEB_PASSWORD
        value: "Giguisa*"
      - key: COOKIE_SECRET
        value: "lYXk6saqrn957gFS56qT-zlZdTdASs6_KKykWMYukJ8"
      - key: PYTHON_VERSION
        value: "3.12.11"

